---
Name: goldfinch-youtube
---
Goldfinch\Youtube\Admin\YoutubeAdmin:
  extensions:
    - Goldfinch\Helpers\Extensions\BlocksAdminExtension
Goldfinch\Youtube\Blocks\YoutubeBlock:
  extensions:
    - Goldfinch\Helpers\Extensions\BaseElementExtension
---
Name: goldfinch-youtube-icon
Only:
  moduleexists: "goldfinch/enchantment"
---
Goldfinch\Youtube\Admin\YoutubeAdmin:
  menu_icon_class: "bi-youtube"

Goldfinch\Youtube\Blocks\YoutubeBlock:
  icon: "bi-youtube"
